### ISSUE TITLE
Release v2.30 --cleanup option not present in setup

### ISSUE THREAD

**Issue by jccurtis** [zoglauer/megalib#10]
The current release (v2.30) includes a default command line arg for `--cleanup` which is not in `setup.sh`. This causes setup.sh to error saying that `--cleanup` is an unknown command. It looks like commit [c2c09b4](https://github.com/zoglauer/megalib/commit/c2c09b4cb74de10360726e55a557f36f3bc27395) addresses this issue but is not in the current release. Adding `--release=dev` to `setup.sh` resolves this error.

**Comment by zoglauer** [comment]
Thanks for reporting.
Fixed it in v2.30 by back porting the --cleanup option
