### ISSUE TITLE
Non-standard license

### ISSUE THREAD

**Issue by stefanv** [zoglauer/megalib#12]
The package is released under a non-standard license.  In practice, this means that few people will be willing to use it.  Consider switching to a well known, standard license?

**Comment by zoglauer** [comment]
Hi Stefan,

I got asked for this before, but this is a not so trivial topic. I remember somebody asked you the same question yesterday, but I did not understand your answer. Do you have some specific suggestions?

Thanks,
Andreas

**Comment by stefanv** [comment]
Sorry for the late response.  I would recommend the BSD license: it does not exclude commercial entities from using your software, nor does it force other researchers to cite your paper.  In practice, it mostly works out well.

If you are particularly concerned about those things, release under a license like the GPL.

**Comment by stefanv** [comment]
Have you again had a chance to consider the license issue?

**Comment by zoglauer** [comment]
Hi Stefan,
Yes, we have decided that version 3.0 - the current experimental branch is the precursor to it - will get a new license.
Cheers,
Andreas

**Comment by stefanv** [comment]
@zoglauer Hi Andreas, out of curiosity: which license have you decided on?

**Comment by zoglauer** [comment]
Hi Stefan,

MEGAlib v3 is now released under GPL v3.

Best,
Andreas
