### ISSUE TITLE
Setup script fails when downloading Geant4 data

### ISSUE THREAD

**Issue by markbandstra** [zoglauer/megalib#13]
A clean install of MEGAlib today on Mac OSX using:

```
git clone https://github.com/zoglauer/megalib MEGAlib
cd MEGAlib
bash setup.sh --release=dev --patch=yes --clean=yes
```

Led to the following error retrieving data for Geant:

```
CMake Error at /Users/<username>/Downloads/MEGAlib/external/geant4_v10.02.p01/geant4_v10.02.p01-build/Externals/G4SAIDDATA-1.1/src/G4SAIDDATA-stamp/download-G4SAIDDATA.cmake:27 (message):
  error: downloading
  'http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz' failed

    status_code: 7
    status_string: "Couldn't connect to server"
    log: Adding handle: conn: 0x7fbe5a803e00

  Adding handle: send: 0

  Adding handle: recv: 0

  Curl_addHandleToPipeline: length: 1

  - Conn 0 (0x7fbe5a803e00) send_pipe: 1, recv_pipe: 0

  About to connect() to geant4.cern.ch port 80 (#0)

    Trying 188.184.163.48...

  Failed connect to geant4.cern.ch:80; Operation timed out

  Closing connection 0
  



make[2]: *** [Externals/G4SAIDDATA-1.1/src/G4SAIDDATA-stamp/G4SAIDDATA-download] Error 1
make[1]: *** [CMakeFiles/G4SAIDDATA.dir/all] Error 2
```

I noticed that you can download the file straight from the [website](http://geant4.cern.ch/support/source). Curiously though, the following command hangs:

```
wget http://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz
```

This command, however, does not (although they need to fix their https certificate):
```
wget https://geant4.cern.ch/support/source/G4SAIDDATA.1.1.tar.gz --no-check-certificate
```

**Comment by jccurtis** [comment]
@markbandstra - At what percentage of compiling GEANT4 do you receive this error?

I receive a similar error downloading http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz This file is a dependency for `G4particles`. I can also download it via:

```
wget http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz --no-check-certificate
```

But not:

```
wget http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz 
```

The error is as follows:

```
[ 18%] Built target G4geometry
Scanning dependencies of target G4particles
CMake Error at /Users/joey/megalib_test/megalib/external/geant4_v10.02.p01/geant4_v10.02.p01-build/Externals/G4ABLA-3.0/src/G4ABLA-stamp/download-G4ABLA.cmake:27 (message):
  error: downloading 'http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz'
  failed

    status_code: 7
    status_string: "Couldn't connect to server"
    log:   Trying 188.184.163.48...

  connect to 188.184.163.48 port 80 failed: Operation timed out

  Failed to connect to geant4.cern.ch port 80: Operation timed out

  Closing connection 0





make[2]: *** [Externals/G4ABLA-3.0/src/G4ABLA-stamp/G4ABLA-download] Error 1
make[1]: *** [CMakeFiles/G4ABLA.dir/all] Error 2
```

**Comment by markbandstra** [comment]
@jccurtis That happened around 7% through.

**Comment by zoglauer** [comment]
Hi Mark & Joe,

Geant4's own installation script initiates the download of all required data files. This happens in the background (or better in one of the threads). Thus an error during download will show up at different progress stages, depending on download and compilation speed.

The problem itself seems to be with Geant4's server.

However, I just tried it myself, and it can download everything now. So maybe the Geant4 server is up and running again.

Could you try again?

Cheers,
Andreas

**Comment by jccurtis** [comment]
I'm running now. I'll update this thread soon

**Comment by jccurtis** [comment]
Unfortunately I'm still unable to download the files. I wonder if this is an LBL network issue? @zoglauer can you wget the files without the `--no-check-certificate` flag?

**Comment by zoglauer** [comment]
Yes, I can:

```
wget http://geant4.cern.ch/support/source/G4ABLA.3.0.tar.gz
```

Gives me the file

**Comment by markbandstra** [comment]
I can download those files using wget now. Rerunning the script now.

**Comment by jccurtis** [comment]
Downloading the files from the server appears to be random. I just tried downloading with `wget` and was able to get the files about 90% of the time. 

@markbandstra were you able to build?

**Comment by markbandstra** [comment]
No, it is failing when building Geant, but for other (unknown) reasons, and after it has downloaded those files.

**Comment by zoglauer** [comment]
Can you copy and paste the error message / last output ?

**Comment by markbandstra** [comment]
My bad, I thought the error was unrelated but I think it was the delay between the failure of a download and the other threads finishing or something. Here is the first error that occurred:

```
[  6%] Building CXX object 
CMake Error at /Users/<username>/Downloads/MEGAlib/external/geant4_v10.02.p01/geant4_v10.02.p01-build/Externals/G4PII-1.3/src/G4PII-stamp/download-G4PII.cmake:27 (message):
  error: downloading 'http://geant4.cern.ch/support/source/G4PII.1.3.tar.gz'
  failed

    status_code: 7
    status_string: "Couldn't connect to server"
    log: Adding handle: conn: 0x7fc84a803e00

  Adding handle: send: 0

  Adding handle: recv: 0

  Curl_addHandleToPipeline: length: 1

  - Conn 0 (0x7fc84a803e00) send_pipe: 1, recv_pipe: 0

  About to connect() to geant4.cern.ch port 80 (#0)

    Trying 188.184.163.48...

  Failed connect to geant4.cern.ch:80; Operation timed out

  Closing connection 0

  



make[2]: *** [Externals/G4PII-1.3/src/G4PII-stamp/G4PII-download] Error 1
make[1]: *** [CMakeFiles/G4PII.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by markbandstra** [comment]
I wanted to add that I have been trying to install on a Ubuntu 14 machine today and running into similar errors (i.e., "Couldn't connect to server" when downloading Geant4 files).

**Comment by zoglauer** [comment]
I try it at home tonight again on my Mac.
If you have the possibility try it via a different network too, to make sure it's not your network blocking it.

**Comment by zoglauer** [comment]
I just tried it at home on my Mac - it also downloads & compiles without issues.

**Comment by markbandstra** [comment]
I re-ran the exact same commands as in the original post and the installation finished successfully today. I suppose the most likely explanation is some kind of network restriction that affected @jccurtis and myself.

**Comment by zoglauer** [comment]
Thanks for the update!

**Comment by jccurtis** [comment]
I also ran the commands last week at LBL on an Ubuntu box with success. The networking restriction has apparently been lifted. I'll make a note if I have further issues. I'm about to build MEGAlib into a [Singularity Image](http://singularity.lbl.gov/) for use on the HPC services at LBL. If successful I could make a PR with the relevant setup/config scripts.
