### ISSUE TITLE
MagaLib setup.sh error with kerberos5

### ISSUE THREAD

**Issue by sarabuson** [zoglauer/megalib#15]
Hallo,

I am experience the following issue when compiling the MagaLib setup.sh. For the record I am using OS X El Capitan (10.11.4):

Scanning dependencies of target G__ASImage
[ 50%] Generating G__ASImage.cxx, ../../lib/libASImage_rdict.pcm, ../../lib/libASImage.rootmap
In file included from input_line_12:6:
In file included from /Users/busonnew/Compair/MegaLib/MEGAlib/external/root_v6.06.06/root_v6.06.06-build/include/TKSocket.h:10:
In file included from /Users/busonnew/Compair/MegaLib/MEGAlib/external/root_v6.06.06/root_v6.06.06-build/include/Krb5Auth.h:47:
/opt/local/include/krb5/krb5.h:8320:10: fatal error: 'et/com_err.h' file not found
#include <et/com_err.h>
         ^
Error: ../../bin/rootcling: compilation failure (/Users/busonnew/Compair/MegaLib/MEGAlib/external/root_v6.06.06/root_v6.06.06-build/lib/libKrb5Authd2f6b90392_dictUmbrella.h)
make[2]: *** [net/krb5auth/G__Krb5Auth.cxx] Error 1
make[1]: *** [net/krb5auth/CMakeFiles/G__Krb5Auth.dir/all] Error 2

If I understood correctly, kerberos5 looks for the file "et/com_err.h"  in the following executable:  /opt/local/include/krb5/krb5.h 

That file is not present in the krb5 directory. I already tried a command-line installation of kerberos5, but nothing changed.

Looking at the ROOT output, there are few other errors reported. Here the file:  
[CMakeError.txt](https://github.com/zoglauer/megalib/files/364692/CMakeError.txt)

Any help would be appreciated. Thanks in advance,
Sara

**Comment by zoglauer** [comment]
Hi Sara,

Are you on a Mac and use homebrew, fink, or mac ports?

If yes try to comment out the respective lines in your .bash_profile (or where ever the tool puts its environment variables).

ROOT does not play nice if additional libraries are installed via those tools on a Mac.

Cheers,
Andreas

**Comment by zoglauer** [comment]
Two more thing to check/try:

(1)
Can you check via
export | grep "/opt/local"
that there is really no reference to macports, I.e the above call returns nothing.

(2)
Alternatively disable krb5 in the root build script:
In the config directory open file "build-root.sh"
In line ~36 add: -Dkrb5=OFF
And call the setup script again.

Cheers,
Andreas

**Comment by zoglauer** [comment]
Something else you could try, but I have never done this before:
Since you already use macports, install root 6.06 via macports

Then switch to the MEAGlib directory, and give the directory where macports has installed ROOT to the setup script, e.g.

bash setup --root=/path/to/macports/version/of/root --rel=dev

**Comment by sarabuson** [comment]
Thanks Andreas, for the records, regarding the first option I tried the first but I realised that krb5 is already disabled, according to the build-root.sh (line 36):

CONFIGUREOPTIONS+="  ....   -Dkerb5=OFF   ..."

so it might may called somewhere else..

**Comment by zoglauer** [comment]
Hi Sara,

Did you get it work by using the root version from macports?

Thanks for the update,
Andreas

**Comment by sarabuson** [comment]
Hi Andrea,

I finally got it working following the same fix of Sylvain. For people reference here the few steps fix:

-- temporary change/rename path of /usr/local/  (because running the setup it will look for MacPorts/Fink stuff here anyway)
-- manually instal cmake
-- run again : bash setup.sh --release=dev

Thanks for your help!
Sara
