### ISSUE TITLE
Errors finding Geant4 files on Mac 10.11.6

### ISSUE THREAD

**Issue by tkburgett** [zoglauer/megalib#18]
@zoglauer I am on a Mac Mini running 10.11.6 and have tried both the standard setup script and the patched dev version (this fixed an error for me on another mac) and both ways I get the four errors displayed showing four missing files: 'G4VSensitiveDetector.hh', 'G4VHit.hh', 'G4TouchableHistory.hh', 'G4ParticleDefinition.hh'.  Doing a search I can verify these files are in fact on my machine but don't know why they can't be found and/or what directory to move them to to resolve this issue. 

I have installed and opened Xcode and have these dependencies installed:

autoconf 2.69
automake 1.15
cmake 3.6.1
curl 7.50.1
gcc 6.1.0_1
git 2.9.3
gmp 6.1.1
isl 0.17.1
libmpc 1.0.3
mpfr 3.1.4

Thanks in advance!

![geant4 files not found](https://cloud.githubusercontent.com/assets/9203135/17722842/899c1e64-63f2-11e6-8c0d-836d3e0d5159.png)

**Comment by tkburgett** [comment]
After placing the previous four files in the /MEGAlib/include directory the errors change to the files shown below. There seems to be a larger problem in the way I set it up that copying the files won't fix....
![geant4 files not found 2](https://cloud.githubusercontent.com/assets/9203135/17723387/f2f11546-63f6-11e6-8bd9-d9209714e949.png)

**Comment by zoglauer** [comment]
That's a new error. I have not seen it before. For some reason the MEGAlib Makefile is unable to find all Geant4 headers.

Try these steps to diagnose this issue:
(1)
Do you use macports, homebrew, or fink?
Those sometimes screw up the environment variables and prevent correct compilation.
It might be a good idea to temporarily comment those out in your bashrc/bash_profile file.

(2) 
Check that Geant4 has been fully compiled.
If you used the default paths then check if a file called 
external/geant4_v10.02.p02/COMPILE_SUCCESSFUL
exists.

(3)
Set up the environment by hand:
M=/path/to/MEGAlib
source /path/to/MEGAlib/config/env.sh --root=/path/to/MEGAlib/external/root_v6.06.06 --geant4=/path/to/MEGAlib/external/geant4_v10.02.p02 --megalib=/path/to/MEGAlib
Obviously you have to use your own path to the MEGAlib directory and whatever root and geant4 version has been installed by the setup script (depends on the MEGAlib version you use)

Then go to the MEGAlib directory and compile again:
./configure 
make 

(4)
If it still doesn't work please send me the output of:
bash config/configure_checkenvironment

(5)
Try to compile some of the Geant4 example programs in 
external/geant4_v10.02.p02/share/Geant4-10.2.2/examples
in see if you can get those to compile

Let me know how it goes,
Andreas

**Comment by tkburgett** [comment]
Apparently X11 was not properly setup which took some time to figure out since the errors the setup was throwing were for other things entirely but it is now working!
