### ISSUE TITLE
build-root.sh resets LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by kialio** [zoglauer/megalib#19]
Hi,

On Line 442 of build-root.sh there is

export LD_LIBRARY_PATH=""

which I assume is there to make sure that old versions of root don't get linked in.  Unfortunately this breaks building on systems that need to point to non-system versions of libraries (our system python and gcc is too old so I have to install user versions of these).  

Jeremy

**Comment by zoglauer** [comment]
Hi Jeremy,

Thanks for pointing this out.

export LD_LIBRARY_PATH=""
is quiet necessary - you can't imaging how screwed up the path's on some computers are... Starting with an empty one prevents many more issues than it creates.

But I will add a new option to the install script to allow to keep the paths - when I am back from my vacation.

Thanks again,
Andreas

**Comment by zoglauer** [comment]
The setup script now has the new option --keepenvironmentasis=on (default: off), which will not reset the LD_LIBRARY_PATH.
It is implemented only in the "experimental" branch which will be MEGAlib 3.0 in the not too far future.
