### ISSUE TITLE
PowerLaw photon energy not in range

### ISSUE THREAD

**Issue by ricrando** [zoglauer/megalib#20]
Hi
when simulating a PowerLaw spectrum, events are generated with energies beyond maximum. Example: source with spectrum as "mySource.Spectrum PowerLaw 100.0 10000.0 1.0"
$ cat allgamma.inc1.id1.sim | grep ED
ED 47532.4
ED 24348.5
ED 423597
ED 74733.2
ED 234.492
ED 25657.1
ED 137781
ED 107752
ED 114414
ED 42453.9
...
By the way BrokenPowerLaw works fine, I am currently using it as a workaround for the spectrum above, as follows:
"BrokenPowerLaw 100 10000 500 1 1"
megalib version is latest, cloned yesterday.

cheers
R

**Comment by zoglauer** [comment]
Hi Riccardo,

Fixed in all 3 main versions (2.30, master, experimental).
The problem only appeared when alpha = 1.0

Thanks for letting me know!
Andreas
