### ISSUE TITLE
New to programming, unfamiliar with cmake and how to resolve

### ISSUE THREAD

**Issue by nkasmanoff** [zoglauer/megalib#24]
Hi, I am in the process of downloading megalib and when following the command (listed in the installation pdf) "bash setup.sh"  in the directory of my choice, I run into this error on step 3: 

Switching to build-root.sh script...
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
ERROR: cmake must be installed
 
ERROR: Something went wrong during the ROOT setup.
 
I downloaded cmake and tried again, but this did not resolve the problem, any advice? 

Thank you, 
 Noah

**Comment by zoglauer** [comment]
Hi Noah,

(1) Install cmake.
(2) Open the cmake program
(3) Somewhere in the menu you find a menu point giving you instructions on how to install the cmake command line tools. 
(4) Follow the instructions. 
(5) Open a new terminal. 
(6) Type "cmake --version"
(7) If you get something like:
cmake version 3.5.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Then you are done. 

Cheers,
Andreas
