### ISSUE TITLE
fatal error: 'fitsio.h' file not found

### ISSUE THREAD

**Issue by reginacaputo** [zoglauer/megalib#25]
I'm compiling MEGAlib on my desktop and am getting this weird error (see below). 
I haven't seen this before and I've compiled MEGAlib quite a few times. fitsio.h exists in this location: 
/opt/local/include

Thanks, 
Regina

Compiling and linking IsotopeFileSplitter ...
Compiling and linking ConvertMGGPOD ...
ConvertMGGPOD.cxx:50:10: fatal error: 'fitsio.h' file not found
#include "fitsio.h"
         ^
1 error generated.
make[2]: *** [/Users/rcaputo2/MEGAlib/bin/ConvertMGGPOD] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [add] Error 2
make: *** [add] Error 2
ERROR: Something went wrong while compiling MEGAlib!

**Comment by reginacaputo** [comment]
Hi Andreas, 
Thanks! I commented that out of the Makefile
I now get the following error. 
Best, 
Regina

Compiling and linking ExternalDataAnalysisExample ...
Compiling and linking ShowHistograms ...
Compiling and linking Revoxelizer ...
make[2]: *** No rule to make target `/Users/rcaputo2/MEGAlib/bin/ConvertMGGPOD', needed by `all'.  Stop.
make[2]: *** Waiting for unfinished jobs....
Compiling and linking IsotopeFileSplitter ...
make[1]: *** [add] Error 2
make: *** [add] Error 2
ERROR: Something went wrong while compiling MEGAlib!

**Comment by zoglauer** [comment]
OK. In the same file, change:

EVERYTHING = $(PRGSX) $(FITS) $(MPI)
to
EVERYTHING = $(PRGSX) $(MPI)

**Comment by reginacaputo** [comment]
Thank you, that compiled it. 

Just for my curiosity - what functionality will I not have by not compiling the cfitsio part? 

Thanks again!

Regina
