### ISSUE TITLE
awk related seg fault

### ISSUE THREAD

**Issue by jccurtis** [zoglauer/megalib#34]
Hi @zoglauer, I'm helping @jhecla to install MEGAlib on an Ubuntu 16.04 laptop and we are getting this a seg fault while running `megalib/bin/source-megalib.sh`. After this `cosima` and `geomega` run for some example cases but I'm not sure if this is a deeper issue. Looking in `/var/crash` we see that the error originates from this call:

```bash
awk BEGIN\ {\ n\ =\ split(\ "G4NDL|G4NEUTRONHPDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4NDL4.5|G4NDL.4.5.tar.gz|fd29c45fe2de432f1f67232707b654c0;G4EMLOW|G4LEDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4EMLOW6.48|G4EMLOW.6.48.tar.gz|844064faa16a063a6a08406dc7895b68;PhotonEvaporation|G4LEVELGAMMADATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/PhotonEvaporation3.2|G4PhotonEvaporation.3.2.tar.gz|01d5ba17f615d3def01f7c0c6b19bd69;RadioactiveDecay|G4RADIOACTIVEDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/RadioactiveDecay4.3.1|G4RadioactiveDecay.4.3.1.tar.gz|e4a1a08a1c26000ffd32f17c38309c6d;G4NEUTRONXS|G4NEUTRONXSDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4NEUTRONXS1.4|G4NEUTRONXS.1.4.tar.gz|665a12771267e3b31a08c622ba1238a7;G4PII|G4PIIDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4PII1.3|G4PII.1.3.tar.gz|05f2471dbcdf1a2b17cbff84e8e83b37;RealSurface|G4REALSURFACEDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/RealSurface1.0|RealSurface.1.0.tar.gz|0dde95e00fcd3bcd745804f870bb6884;G4SAIDDATA|G4SAIDXSDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4SAIDDATA1.1|G4SAIDDATA.1.1.tar.gz|d88a31218fdf28455e5c5a3609f7216f;G4ABLA|G4ABLADATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4ABLA3.0|G4ABLA.3.0.tar.gz|d7049166ef74a592cb97df0ed4b757bd;G4ENSDFSTATE|G4ENSDFSTATEDATA|/home/jake/Documents/InstallScripts-master/Ubuntu/GEANT4.10.2.p1/geant4-build/data/G4ENSDFSTATE1.2.1|G4ENSDFSTATE.1.2.1.tar.gz|55eba9a1fc69626ac8eb0eb40330acf9",\ array,\ ";")
```

I've attached the crash log file. 

[_usr_bin_mawk.1000.crash.txt](https://github.com/zoglauer/megalib/files/1861531/_usr_bin_mawk.1000.crash.txt)

This may be related to an environment issues on this machine or the version of `awk` (`mawk`) is not compatible (we've reinstalled it.) We wanted to check with you before wiping the OS and starting over. Thanks!

**Comment by zoglauer** [comment]
You seem to have installed mawk, the default on Ubuntu16.04  is gawk.
Could you switch to gawk?

sudo update-alternatives --config awk

then choose gawk

**Comment by jccurtis** [comment]
My aplogies for the delayed response. @jhecla, can you try this?

@zoglauer, is this C call to the AWK string operation specific to GAWK?

**Comment by zoglauer** [comment]
I do not know. I just know that on all systems we use gawk and not mawk.

**Comment by jccurtis** [comment]
Thanks @zoglauer, after an `update-alternatives` did the trick! Closing
