### ISSUE TITLE
XMING running but no Xclient spawned

### ISSUE THREAD

**Issue by rquerrar** [zoglauer/megalib#38]
I have installed MEGAlib on a Windows10 machine using the Ubuntu App method. Xming server is installed and running. But when geomega (for example) is called, it exits with an error that no x-client seems to start. The specific output to the cmd line before exiting is: "No X-client or ROOT in batch mode: Using batch mode.."

Can anyone offer ideas on why the x11 client for the MEGAlib applications don't seem to be starting?

Thanks

**Comment by zoglauer** [comment]
Hi Rodney,

Can you open other X11 applications? For example xterm?
Or are just the MEGAlib applications not working?

Best,
Andreas

**Comment by rquerrar** [comment]
I believe other x11 apps are ok. For example I've connected to a remote machine using putty. The Xserver is running in my task bar. I am not sure what other x11 apps I have that I can test it with though. Thanks for the help.

**Comment by zoglauer** [comment]
Open a bash prompt and type:
xterm &
Do you get a window with another terminal?

**Comment by rquerrar** [comment]
Ah - yes, I can get an xterm from my unbuntu bash shell. 

And..having done that I just ran geomega from inside that xterm and I get the x11 GUI just fine now. So I guess that's the answer? The x11 tools have to run from inside an xterm (rather than just inside the ubuntu app window)? Thanks again for the help.

**Comment by zoglauer** [comment]
Usually I can just run all of the MEGAlib UI programs from any bash terminal. I do not know what might cause the problem in your case.

Which Windows 10 release and which Ubuntu version are you using?

**Comment by rquerrar** [comment]
I am using Windows 10 Home Version 1803 and as for Ubuntu I am using Version 1604.2018.510.0

**Comment by zoglauer** [comment]
Where you able to get it to run?
For me MEGAlib works with the latest version of Windows and Ubuntu 1604

**Comment by zoglauer** [comment]
I was able to reproduce this error on a fresh installation of Windows 10 1803 with Ubuntu from the Microsoft store.

In order to get X to work you have to set 
export DISPLAY=localhost:0.0
in your .bashrc
