### ISSUE TITLE
mulltiple download and/or compile issues with GEANT4 for different files

### ISSUE THREAD

**Issue by jacobrsmith** [zoglauer/megalib#40]
both times that I've run the setup script there have been download/compiling errors from GEANT4. In both cases the downloads reported as 100%.

here are the two files
G4EMLOW.6.48.tar.gz
G4NDL.4.5.tar.gz

Below are the reports from both occurrences. 

Thank you

Start of First Occurrence 
================================================

[100%] Building CXX object source/visualization/OpenGL/CMakeFiles/G4OpenGL.dir/src/G4OpenGLStoredXViewer.cc.o
[100%] Building CXX object source/visualization/OpenGL/CMakeFiles/G4OpenGL.dir/src/G4OpenGLXViewer.cc.o
[100%] Linking CXX shared library ../../../BuildProducts/lib/libG4OpenGL.so
[100%] Built target G4OpenGL

CMake Error at /home/jacob/MEGAlib/external/geant4_v10.02.p03/geant4_v10.02.p03-build/Externals/G4EMLOW-6.48/src/G4EMLOW-stamp/download-G4EMLOW.cmake:27 (message):
  error: downloading
  'http://geant4.cern.ch/support/source/G4EMLOW.6.48.tar.gz' failed

    status_code: 28
    status_string: "Timeout was reached"
    log:   Trying 188.184.9.235...

  Connected to geant4.cern.ch (188.184.9.235) port 80 (#0)

  GET /support/source/G4EMLOW.6.48.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 302 Found

  Content-Type: text/html; charset=utf-8

  Location: http://geant4.web.cern.ch/support/source/G4EMLOW.6.48.tar.gz

  Server: Microsoft-IIS/8.5

  X-Powered-By: ASP.NET

  Date: Wed, 18 Jul 2018 18:34:02 GMT

  Content-Length: 177

  

  Ignoring the response-body

  [177 bytes data]

  Connection #0 to host geant4.cern.ch left intact

  Issue another request to this URL:
  'http://geant4.web.cern.ch/support/source/G4EMLOW.6.48.tar.gz'

    Trying 188.184.37.205...

  Connected to geant4.web.cern.ch (188.184.37.205) port 80 (#1)

  GET /support/source/G4EMLOW.6.48.tar.gz HTTP/1.1

  Host: geant4.web.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Date: Wed, 18 Jul 2018 18:34:03 GMT

  Server: Apache

  X-Drupal-Cache: MISS

  Expires: Sun, 19 Nov 1978 05:00:00 GMT

  Cache-Control: no-cache, must-revalidate

  X-Content-Type-Options: nosniff

  Location:
  http://geant4-data.web.cern.ch/geant4-data/datasets/source/G4EMLOW.6.48.tar.gz

  Content-Length: 0

  Content-Type: text/html; charset=UTF-8

  Via: 1.1 drupallb01.cern.ch

  Set-Cookie: drupallb01_80=.drupal13; path=/;HttpOnly

  

  Connection #1 to host geant4.web.cern.ch left intact

  Issue another request to this URL:
  'http://geant4-data.web.cern.ch/geant4-data/datasets/source/G4EMLOW.6.48.tar.gz'

    Trying 137.138.150.3...

  Connected to geant4-data.web.cern.ch (137.138.150.3) port 80 (#2)

  GET /geant4-data/datasets/source/G4EMLOW.6.48.tar.gz HTTP/1.1

  Host: geant4-data.web.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 200 OK

  Date: Wed, 18 Jul 2018 18:34:04 GMT

  Server: Apache

  Last-Modified: Wed, 28 Oct 2015 09:47:22 GMT

  ETag: "3c828fbf0000000-1832278-5232714ba3e80"

  Accept-Ranges: bytes

  Content-Length: 25371256

  Access-Control-Allow-Origin: https://geant4-tools.web.cern.ch

  Access-Control-Allow-Methods: GET,HEAD,OPTIONS

  Access-Control-Expose-Headers:
  Content-Length,Content-Type,Content-Encoding

  Connection: close

  Content-Type: application/x-gzip

  Content-Encoding: x-gzip

  

  [3642 bytes data]

  [8244 bytes data]

  [1374 bytes data]
....
many of these types of lines repeat
....
  [1374 bytes data]

  [9618 bytes data]

  Operation timed out after 14398914 milliseconds with 25355316 out of
  25371256 bytes received

  Closing connection 2

  

make[2]: *** [Externals/G4EMLOW-6.48/src/G4EMLOW-stamp/G4EMLOW-download] Error 1
CMakeFiles/G4EMLOW.dir/build.make:89: recipe for target 'Externals/G4EMLOW-6.48/src/G4EMLOW-stamp/G4EMLOW-download' failed
make[1]: *** [CMakeFiles/G4EMLOW.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:390: recipe for target 'CMakeFiles/G4EMLOW.dir/all' failed
Makefile:149: recipe for target 'all' failed
ERROR: Something went wrong while compiling Geant4!
 
ERROR: Something went wrong during the Geant4 setup.
 
       Please take a look if you find the issue here (look at open and closed issues):
       https://github.com/zoglauer/megalib/issues
       If not add your problem and write me an email!
 
jacob@jandahpg ~/MEGAlib $ 

=================================================
end of first occurrence 
=================================================

Start of Second occurrence
=================================================

[100%] Building CXX object source/visualization/OpenGL/CMakeFiles/G4OpenGL.dir/src/G4OpenGLStoredXViewer.cc.o
[100%] Building CXX object source/visualization/OpenGL/CMakeFiles/G4OpenGL.dir/src/G4OpenGLXViewer.cc.o
[100%] Linking CXX shared library ../../../BuildProducts/lib/libG4OpenGL.so
[100%] Built target G4OpenGL
CMake Error at /home/jacob/MEGAlib/external/geant4_v10.02.p03/geant4_v10.02.p03-build/Externals/G4NDL-4.5/src/G4NDL-stamp/download-G4NDL.cmake:27 (message):
  error: downloading 'http://geant4.cern.ch/support/source/G4NDL.4.5.tar.gz'
  failed

    status_code: 28
    status_string: "Timeout was reached"
    log:   Trying 188.184.9.235...

  Connected to geant4.cern.ch (188.184.9.235) port 80 (#0)

  GET /support/source/G4NDL.4.5.tar.gz HTTP/1.1

  Host: geant4.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 302 Found

  Content-Type: text/html; charset=utf-8

  Location: http://geant4.web.cern.ch/support/source/G4NDL.4.5.tar.gz

  Server: Microsoft-IIS/8.5

  X-Powered-By: ASP.NET

  Date: Thu, 19 Jul 2018 14:00:04 GMT

  Content-Length: 174

  

  Ignoring the response-body

  [174 bytes data]

  Connection #0 to host geant4.cern.ch left intact

  Issue another request to this URL:
  'http://geant4.web.cern.ch/support/source/G4NDL.4.5.tar.gz'

    Trying 188.184.37.205...

  Connected to geant4.web.cern.ch (188.184.37.205) port 80 (#1)

  GET /support/source/G4NDL.4.5.tar.gz HTTP/1.1

  Host: geant4.web.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Date: Thu, 19 Jul 2018 14:00:05 GMT

  Server: Apache

  X-Drupal-Cache: MISS

  Expires: Sun, 19 Nov 1978 05:00:00 GMT

  Cache-Control: no-cache, must-revalidate

  X-Content-Type-Options: nosniff

  Location:
  http://geant4-data.web.cern.ch/geant4-data/datasets/source/G4NDL.4.5.tar.gz

  Content-Length: 0

  Content-Type: text/html; charset=UTF-8

  Via: 1.1 drupallb01.cern.ch

  Set-Cookie: drupallb01_80=.drupal14; path=/;HttpOnly

  

  Connection #1 to host geant4.web.cern.ch left intact

  Issue another request to this URL:
  'http://geant4-data.web.cern.ch/geant4-data/datasets/source/G4NDL.4.5.tar.gz'

    Trying 137.138.150.3...

  Connected to geant4-data.web.cern.ch (137.138.150.3) port 80 (#2)

  GET /geant4-data/datasets/source/G4NDL.4.5.tar.gz HTTP/1.1

  Host: geant4-data.web.cern.ch

  User-Agent: curl/7.47.0

  Accept: */*

  

  HTTP/1.1 200 OK

  Date: Thu, 19 Jul 2018 14:00:06 GMT

  Server: Apache

  Last-Modified: Tue, 19 Aug 2014 10:26:16 GMT

  ETag: "3c8325c70000000-1922c9d6-500f8eae02200"

  Accept-Ranges: bytes

  Content-Length: 421710294

  Access-Control-Allow-Origin: https://geant4-tools.web.cern.ch

  Access-Control-Allow-Methods: GET,HEAD,OPTIONS

  Access-Control-Expose-Headers:
  Content-Length,Content-Type,Content-Encoding

  Connection: close

  Content-Type: application/x-gzip

  Content-Encoding: x-gzip

  

  [892 bytes data]

  [1374 bytes data]

  [1374 bytes data]
....
many of these lines repeat
....
  [1374 bytes data]

  [2748 bytes data]

  Operation timed out after 14397529 milliseconds with 42555046 out of
  421710294 bytes received

  Closing connection 2

  

make[2]: *** [Externals/G4NDL-4.5/src/G4NDL-stamp/G4NDL-download] Error 1
CMakeFiles/G4NDL.dir/build.make:89: recipe for target 'Externals/G4NDL-4.5/src/G4NDL-stamp/G4NDL-download' failed
make[1]: *** [CMakeFiles/G4NDL.dir/all] Error 2
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/G4NDL.dir/all' failed
make: *** [all] Error 2
Makefile:149: recipe for target 'all' failed
ERROR: Something went wrong while compiling Geant4!
 
ERROR: Something went wrong during the Geant4 setup.
 
       Please take a look if you find the issue here (look at open and closed issues):
       https://github.com/zoglauer/megalib/issues
       If not add your problem and write me an email!
 
jacob@jandahpg ~/MEGAlib $ 

======================================
end of second occurrence
======================================

**Comment by zoglauer** [comment]
Hi Jacob,

There seems to be an issue with the Geant4 download servers at the moment -- everything is very slow.
You could increase the timeout in config/build-geant4.sh:
Line 10, find: -DGEANT4_INSTALL_DATA_TIMEOUT=14400 and add a zero.

Best,
Andreas

**Comment by zoglauer** [comment]
Just another thought: You are using a current version right?
Because they changed the location of where all the Geant4 files are roughly a month ago and I had to fix the script.

Could you check that you use either the master, the experimental, or version 2.34?

**Comment by jacobrsmith** [comment]
For the MEGAlib version, I did 
$ git clone https://github.com/zoglauer/megalib MEGAlib

and according to doc/ChangeLog.txt ...
"Version 2.33/2.34"
 
So I think I have version 2.34. I do not think I have either the master or experimental.

I'm currently trying the increased timeout. I've also downloaded the individual GEANT4 v10.2 Data files and will try to put them in the right place for MEGAlib to detect and avoid the downloading phase.

Jacob

**Comment by jacobrsmith** [comment]
increasing the timeout did not work. all dataset files but one downloaded. G4NDL.4.5.tar.gz did not finish downloading and the file size stopped increasing for a long time. It got to 23113762 out of 421710294. 

I'd like to try two other solutions.
(1) make MEGAlib use the dataset files I downloaded myself 
(2) change the download site that MEGAlib is trying to access. 
I tried the first (failed) but not the second. Details are below.

**Solution #1 (make MEGAlib use the dataset files I downloaded myself)**
I can download each dataset file individually from the G4 website. G4 version 10.2 uses G4NDL.4.5.tar.gz.

Is there a way I can force MEGAlib to use the files I downloaded so that MEGAlib doesnt try to download the files?

I tried to copy them all to ~/MEGAlib/externals, but that doesnt work. Doesn't work means that MEGAlib tries to download the dataset files.
I also tried to copy them to ~/MEGAlib, but that doesnt work. 

**Solution #2 (change where MEGAlib accesses G4 datasets)**
It seems that the location of the datasets online is 
http://cern.ch/geant4-data/datasets/G4NDL.4.5.tar.gz

but I dont see that MEGAlib is attempting to download from that location.

Alternatively, if I cannot make MEGAlib use the files I downloaded, can I change where MEGAlib attempts the download?

**Comment by zoglauer** [comment]
Hi Jacob,

I was able to install it on my machine, it just takes a few hours to download all the data sets.

In general, the downloads are handled internally by the geant4 cmake process, which my script calls. So I cannot change the places where is looks for the download, those are hard-coded in the Geant4 internal scripts.

My script basically just follows the instructions in this manual:

http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/InstallationGuide/html/installguide.html

You can try to follow it too and install the data sets manually.
When you run cmake by hand, just make sure you use the same flags as here:
https://github.com/zoglauer/megalib/blob/master/config/build-geant4.sh
Line 10

Then in the MEGAlib setup script, use the option --geant4=<path to your installation> and it will not try to install geant4 by itself.

Best,
Andreas
