### ISSUE TITLE
is only available from C++17 onwards

### ISSUE THREAD

**Issue by aleita** [zoglauer/megalib#42]
I'm trying to compile MEGAlib but at the end I always get to the following error:
I also tried to specify -std=c++17/ -std=gnu++17 config/Makefile.linxgcc.

/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.14.02-c2be2/x86_64-centos7-gcc8-opt/include/TString.h:110:13: error: expected type-specifier
    operator std::string_view() const { return std::string_view(Data(),fExtent); }
             ^~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.14.02-c2be2/x86_64-centos7-gcc8-opt/include/TString.h:275:23: error: ‘string_view’ in namespace ‘std’ does not name a type
    TString(const std::string_view &sub);
                       ^~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.14.02-c2be2/x86_64-centos7-gcc8-opt/include/TString.h:275:18: note: ‘std::string_view’ is only available from C++17 onwards
    TString(const std::string_view &sub);

is there a certain version conbination between all the components [gcc 8.2, cmake 3.12, binutil 2.30, ROOT 6.14.02, GENAT4 10.02.p02] which is supposed to work ?

thanks in advance

**Comment by aleita** [comment]
in the above example I used the CERN one in particular 

/cvmfs/sft.cern.ch/lcg/releases/ROOT/6.14.02-c2be2/x86_64-centos7-gcc8-opt/ /cvmfs/sft.cern.ch/lcg/releases/Geant4/10.02.p02-63aaa/x86_64-centos7-gcc62-opt/

I've an ongoing attempt to compile ROOT using the setup script

**Comment by zoglauer** [comment]
OK. Let me know how your compile attempt goes.
Because the error message looks like you used a different setup for compiling MEGAlib than what was used to compile ROOT. Is this possible?

**Comment by aleita** [comment]
This is the point, find the right environment/config in order to have a working copy of the code.
I've done several attempts using different version of the various components [gcc , cmake , binutil , ROOT , GENAT4] but at the end the one posted in this issue seems to me the one closest  to the solution.

have you already seen this error message " is only available from C++17 onwards" ?

**Comment by zoglauer** [comment]
The setup script compiles all necessary libraries, thus this problem should normally not appear.
I have seen similar problems with centos, yes.

If everything fails, just a few weeks back I made my first MEGAlib docker:
https://hub.docker.com/r/zoglauer/megalib

Feel free to try that one.

**Comment by aleita** [comment]
OUTPUT using the setup script

[ 98%] Linking CXX shared library ../../lib/libProofBench.so
[100%] Built target ProofBench
Scanning dependencies of target ProofBenchPARFiles
[100%] Generating ../../etc/proof/proofbench/ProofBenchCPUSel.par, ../../etc/proof/proofbench/ProofBenchDataSel.par
[100%] Built target ProofBenchPARFiles
Scanning dependencies of target pq2
[100%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/pq2actions.cxx.o
[100%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/pq2main.cxx.o
[100%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/pq2ping.cxx.o
[100%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/pq2wrappers.cxx.o
[100%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/redirguard.cxx.o
[100%] Linking CXX executable ../../bin/pq2
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/tmp/MEGAlib/external/root_v6.14.02/root_v6.14.02-build/lib/libtbb.so.2: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pq2] Error 1
make[1]: *** [proof/pq2/CMakeFiles/pq2.dir/all] Error 2
make: *** [all] Error 2


bash-4.2$ echo $LD_LIBRARY_PATH
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-70db8/x86_64-centos7-gcc62-opt//lib/:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.1.0/x86_64-centos7/lib64/:/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/:

bash-4.2$ echo $LD_RUN_PATH
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-70db8/x86_64-centos7-gcc62-opt/lib/:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.1.0/x86_64-centos7/lib64/

bash-4.2$ echo $PATH
/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-70db8/x86_64-centos7-gcc62-opt//bin/:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.1.0/x86_64-centos7/bin/:/cvmfs/sft.cern.ch/lcg/releases/CMake/3.11.1-773ff/x86_64-centos7-gcc8-opt/bin:/opt/exp_soft/glast_local/HealPix/latest/bin_F90:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/java/jdk1.5.0_14/bin/:/opt/exp_soft/glast_local/bin

**Comment by aleita** [comment]
ROOT building process failed due to an "undefined reference " for tbb library.

same result even if the ROOT setup script build tbb library by itself

in the following example I tried to use the CERN one

[ 98%] Building CXX object proof/pq2/CMakeFiles/pq2.dir/src/redirguard.cxx.o
[ 98%] Linking CXX executable ../../bin/pq2
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/cvmfs/sft.cern.ch/lcg/releases/tbb/44_20160413-f254c/x86_64-centos7-gcc7-opt/lib/libtbb.so.2: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/pq2] Error 1
make[1]: *** [proof/pq2/CMakeFiles/pq2.dir/all] Error 2
make: *** [all] Error 2
ERROR: Something went wrong while compiling ROOT!
 
ERROR: Something went wrong during the ROOT setup.
 
       Please take a look if you find the issue here (look at open and closed issues):
       https://github.com/zoglauer/megalib/issues
       If not add your problem and write me an email!

**Comment by zoglauer** [comment]
I installed exactly this CentOS version, switched to the latest devtools, and MEGAlib installed without problems.

I strongly suggest you check your environment variables. For some reason ROOT finds a libtbb.so, which seems to be compiled with a different compiler.

**Comment by aleita** [comment]
You are definitely right.
I’ve just installed cmake3 and devtoolset-7
and I finally managed to install MEGAlib, ROOT AND G4. 

Thanks for your help and patience

Ale

**Comment by zoglauer** [comment]
Great!
