### ISSUE TITLE
RSP Files to use in xspec

### ISSUE THREAD

**Issue by mikemoss3** [zoglauer/megalib#45]
Hello Andreas,

Sorry to bother you again so quickly.

I am trying to generate response files for AMEGO simulations. Is this possible and, if so, what are the necessary steps?

I am aware of the ResponseCreator function in Megalib and I have executed it as follows:

`
 responsecreator -g path/to/Geometry.geo.setup -f FileName.inc1.id1.sim -m s -r response-test
`

Where I used actual files for the .geo.setup and .sim files (I can send them to you upon request). 

The .rsp files that are generated are not accessible by rmfit or xspec, as it is not in the proper readable format for those programs. Is there a way to place them into this proper format? Maybe there is an option I need to specify.

Let me know what information you need from me! 

Respectfully, 
Michael Moss

**Comment by zoglauer** [comment]
Those are MEGAlib spectral response files. You need a second program to convert from the rsp to a xspec response file.
I'll send you an email.
