### ISSUE TITLE
ROOT compilation FREETYPE Error with macOS 10.14 Mojave

### ISSUE THREAD

**Issue by dashmanix** [zoglauer/megalib#52]
Problems with freetype during ROOT compilations, this is the Error:
.....
[ 58%] Built target ClangAttrDump
[ 58%] Built target ClangCommentHTMLTags
[ 58%] Built target ClangDeclNodes
CMake Error at /Users/Documents/Simulation_Mont_Carlo/ROOT/root-6.16.00-build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-build-RelWithDebInfo.cmake:49 (message):
  Command failed: 2

   '/Applications/Xcode.app/Contents/Developer/usr/bin/make'

  See also

    /Users/Documents/Simulation_Mont_Carlo/ROOT/root-6.16.00-build/FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-build-*.log

make[2]: *** [FREETYPE-prefix/src/FREETYPE-stamp/FREETYPE-build] Error 1
make[1]: *** [CMakeFiles/FREETYPE.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Built target ClangAttrVisitor
[ 58%] Built target ClangDiagnosticCommon
[ 58%] Built target ClangARMNeon
make: *** [all] Error 2

**Comment by zoglauer** [comment]
Could you send me the complete log file?

**Comment by dashmanix** [comment]
> Could you send me the complete log file?

log file : ..../FREETYPE-build-*.log
--------------
/opt/local/bin/ranlib: object: /Users/Documents/Simulation_Mont_Carlo/ROOT/root-6.16.00-build/FREETYPE-prefix/src/FREETYPE/objs/.libs/libfreetype.a(ftsystem.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
make[3]: *** [/Users/Documents/Simulation_Mont_Carlo/ROOT/root-6.16.00-build/FREETYPE-prefix/src/FREETYPE/objs/libfreetype.la] Error 1
--------------

**Comment by zoglauer** [comment]
Googling a bit, you will find that the most common reason for this problem is that your Xcode command line tools are either old or broken.

Could you do
`xcode-select --install`
and try again?
