### ISSUE TITLE
Add documentation about XQuartz to setup page

### ISSUE THREAD

**Issue by marwahaha** [zoglauer/megalib#53]
Cool project 👍 

I got the install working via `./setup.sh` on my Mac running Sierra 10.12.6. I did not have Geant or ROOT before this install. 

Only one hiccup:
There was an issue when the `cmake` command installing Geant was looking for X11, and my machine didn't have have it.  Looks like Apple doesn't install it by default anymore -- https://support.apple.com/en-us/HT201341 , but it's a simple install! https://www.xquartz.org/

After installing, the `./setup.sh` script worked great!

**Comment by zoglauer** [comment]
Hello,

Thanks!
The xquartz information is already included in the extended setup manual, which is linked from the main README.md:
http://megalibtoolkit.com/setup.html
Section "Additional information for macOS"

Best,
Andreas

**Comment by marwahaha** [comment]
Thanks, I missed that!
