### ISSUE TITLE
ROOT v6.14.08 fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by LaHaine** [zoglauer/megalib#55]
I have tried building megalib in a Ubuntu 18.04 container with the command ./setup.sh . It failed like this:
```
[ 58%] Copying
/tmp/waschk/megalib/external/root_v6.14.08/root_v6.14.08-source/macros/Dialogs.C
[ 58%] Built target move_artifacts
-- LZMA build command succeeded.  See also
/tmp/waschk/megalib/external/root_v6.14.08/root_v6.14.08-build/LZMA-prefix/src/LZMA-stamp/LZMA-build-*.log
[ 58%] Performing install step for 'LZMA'
-- AFTERIMAGE build command succeeded.  See also
/tmp/waschk/megalib/external/root_v6.14.08/root_v6.14.08-build/AFTERIMAGE-prefix/src/AFTERIMAGE-stamp/AFTERIMAGE-build-*.log
[ 58%] Performing install step for 'AFTERIMAGE'
-- AFTERIMAGE install command succeeded.  See also
/tmp/waschk/megalib/external/root_v6.14.08/root_v6.14.08-build/AFTERIMAGE-prefix/src/AFTERIMAGE-stamp/AFTERIMAGE-install-*.log
[ 58%] Completed 'AFTERIMAGE'
[ 58%] Built target AFTERIMAGE
-- LZMA install command succeeded.  See also
/tmp/waschk/megalib/external/root_v6.14.08/root_v6.14.08-build/LZMA-prefix/src/LZMA-stamp/LZMA-install-*.log
[ 58%] Completed 'LZMA'
[ 58%] Built target LZMA
make: *** [all] Error 2
Makefile:151: recipe for target 'all' failed
ERROR: Something went wrong while compiling ROOT!

ERROR: Something went wrong during the ROOT setup.

       Please take a look if you find the issue here (look at open and
closed issues):
       https://github.com/zoglauer/megalib/issues
       If not add your problem and write me an email!
```
The only error from config/configure_packages is about graphviz-dev which is now called libgraphviz-dev.
[RootBuildLog.txt](https://github.com/zoglauer/megalib/files/4392612/RootBuildLog.txt)

**Comment by zoglauer** [comment]
The build log does not show what goes wrong, it seems to just stop.
Could you switch to the experimental branch and try again?

There is also a Dockerfile in the experimental branch which you could use.

**Comment by LaHaine** [comment]
With the experimental branch I get the same error from the ROOT build. 

BTW I'm using a Singularity container, not Docker.

**Comment by LaHaine** [comment]
I have just tested, the version of root downloaded by megalib (v6.14.08) built just fine with the default options on Ubuntu 18.04.

**Comment by zoglauer** [comment]
Are you still using a container?
Ubuntu 18.04 is my default development system and MEGAlib should installs without errors

**Comment by LaHaine** [comment]
Yes, that's in the very same container.

**Comment by zoglauer** [comment]
I have never tested that container.
Can you let me know what you do to set it up, so that I can try and reproduce the problem?

**Comment by LaHaine** [comment]
Oh, it is a pretty generic singularity container of Ubuntu 18.04 with a lot of standard software installed. I'll try to bake a singularity recipe that could be used by you.

**Comment by LaHaine** [comment]
This creates a simple container with the command `singularity build ubuntu.sif Singularity.txt
`
Then execute the container with `singularity shell ubuntu.sif` and run the megalib build.
[Singularity.txt](https://github.com/zoglauer/megalib/files/4394288/Singularity.txt)

**Comment by zoglauer** [comment]
I got it to run with this singularity definition file:
[MEGAlib.txt](https://github.com/zoglauer/megalib/files/4394662/MEGAlib.txt)

After you launch singularity do:
git clone https://github.com/zoglauer/megalib.git MEGAlib
cd MEGAlib/
git checkout experimental
bash setup.sh --rel=dev --br=experimental

Then follow the final instructions on screen to setup your environment

**Comment by LaHaine** [comment]
I'll try that

**Comment by LaHaine** [comment]
OK, it built, thanks for your help.
