### ISSUE TITLE
Difficulty in installing Megalib in windows

### ISSUE THREAD

**Issue by adebnath79** [zoglauer/megalib#57]
I am trying to install Megalib in windows. But I am having difficulty in doing that.
 1. I Have installed the windows subsystem for linux
2. Installed Ubuntu app from windows store.
3.Installed Xming X server for windows
4.Ran the Bash app and trying to install Megalib in the bash prompt of Ubuntu app. When I put the command $ bash setup.sh -- it says no file or directory.

**Comment by zoglauer** [comment]
Did you do the following steps:
git clone https://github.com/zoglauer/megalib MEGAlib
cd MEGAlib
bash setup.sh

**Comment by adebnath79** [comment]
No I didnt do git clone. Ok I will do that and will let you know.
Thank you very much.
Ananya.

**Comment by adebnath79** [comment]
I downloaded the Megalib zip file. Is there a set up file which I have to run?

**Comment by adebnath79** [comment]
I see I have to run the script $ git clone https://github.com/zoglauer/megalib MEGAlib. I got it now.
Thanks.

**Comment by Yugadeep** [comment]
were you able to get it working? I'm trying to install megalib in windows as well but it is running into so many errors

**Comment by zoglauer** [comment]
I have it running under windows with Ubuntu 22.04 under WSL. Please open a new ticket with your error messages. Please use the main branch of MEGAlib.

**Comment by Yugadeep** [comment]
@zoglauer , thank you so much for the quick reply. I was actually able to finish the installation after realizing that my errors were about my computer running out of memory. I followed Cyrus008's advice on this [website](https://github.com/soedinglab/hh-suite/issues/280#issuecomment-1076146671) to increase the swap file memory and it somehow worked.

Could I please ask if there are any resources or tutorials on how to get started using geomega and cosima? I know there is resource/examples. And I understand what the files mean and what how I can change the values. But how do I run the geomega and cosima softwares to run the simulations on the files? I have read your original publication [paper ](https://www.sciencedirect.com/science/article/abs/pii/S1387647306000832?casa_token=eWASIE9WoLkAAAAA:akHu9Crnpu9DqQFxa_-Daguw7GsLrOEf0ht8JczLS7oahfTSp0r-nCPEorcJS9yKSIF7huSanO8 ) describing the applications and what each file looks like. But I don't know how to run the softwares.

I really only need to measure the number of hits at the detectors once the source starts emitting radiation. So I don't think I will need to do high-level analysis, just somehow count the hits. I know this space is not for skill issues but I would really appreciate any help you can give me. Thank you! I appreciate you still responding to these issues after all these years.

**Comment by zoglauer** [comment]
Email me, I do have a few pdfs for you.

**Comment by Yugadeep** [comment]
Done, I sent it to your Berkeley email. Thanks a lot!
