### ISSUE TITLE
Error with Geant4 sourcing

### ISSUE THREAD

**Issue by AdityaRoot** [zoglauer/megalib#63]
Hi, I am installing MEGAlib on an arch linux install and have had a few errors.

Notably I changed the AllowedGeant4Versions.txt and AllowedROOTVersions.txt to install newer versions of both. With the latter this fixed the issues I was having during compilation however with Geant4 I am failing at the sourcing step.

Upon running the source command `source /home/adi/MEGAlib/bin/source-megalib.sh` I receive the following error:
`bash: cd: /usr/bin/../../../include/Geant4: No such file or directory`

I looked at the code of source-megalib.sh and tried defining the different environments manually one at a time through the config/env.sh and both --root and --megalib's sources work correctly and solely geant's gives the above error. Going through env.sh, nothing looks like it would lead to the path /usr/bin/../../../include/Geant4 in the first place.

I receive this error regardless of the Geant4 version set in AllowedGeant4Versions.txt

**Comment by zoglauer** [comment]
You cannot switch the versions of Geant4 due to API changes,
Did you let the MEGAlib setup script install Geant4?

**Comment by AdityaRoot** [comment]
Yes I let the setup script install after changing the version in the allowed versions file - I'll try changing it back and get the error.

**Comment by AdityaRoot** [comment]
Just recompiled - the compilation says success however I get the exact same error upon using the source command.

**Comment by zoglauer** [comment]
Yes, you can update ROOT.
I am trying to install Arch at the moment in a virtual machine and try to reproduce the error.
Might take a while.

**Comment by zoglauer** [comment]
The default MEGAlib install is now working on Arch with the latest version on the master branch.
