### ISSUE TITLE
Track Quality Factor for pair events

### ISSUE THREAD

**Issue by henrikef** [zoglauer/megalib#64]
https://github.com/zoglauer/megalib/blob/fa69779b9f22dc682da1c77883899ea92d2d52be/src/revan/src/MRERawEvent.cxx#L1114
https://github.com/zoglauer/megalib/blob/fa69779b9f22dc682da1c77883899ea92d2d52be/src/revan/src/MRERawEvent.cxx#L1115

Is there a typo in the code above or if the track quality for pair events or is it really supposed to be just the quality of the electron track (independent of the positron track)?

**Comment by zoglauer** [comment]
That's a bug. I'll fix it when I am back from vacation.
Thanks, Henrike!

**Comment by zoglauer** [comment]
Fixed in master
