### ISSUE TITLE
Compilation failure due to a conflict between GSL and ROOT   

### ISSUE THREAD

**Issue by alanchiu214** [zoglauer/megalib#7]
Affected version: ROOT 5.34.34   
File with trouble: root-5-34-34/math/mathmore/src/GSLMultiFit.h   
Mac OS X: El Capitan  
GSL: 1.5 & 2.0 (installed for different codes)  

I had a compilation failure on ROOT due to a conflict raised from different GSL versions it pointed. Attached is the error message (referred from internet).   

------   
:info:build /usr/bin/clang++ -O2 -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Iinclude -DR__HAVE_CONFIG    -std=c++11 -stdlib=libc++   -pthread -I/opt/local/include  -DUSE_ROOT_ERROR -o math/mathmore/src/GSLRootFinderDeriv.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_root5/root5/work/root-5-34-34/math/mathmore/src/GSLRootFinderDeriv.cxx
:info:build In file included from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_root5/root5/work/root-5-34-34/math/mathmore/src/GSLNLSMinimizer.cxx:19:
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_root5/root5/work/root-5-34-34/math/mathmore/src/GSLMultiFit.h:142:38: error: no member named 'J' in 'gsl_multifit_fdfsolver'
:info:build       gsl_multifit_gradient(fSolver->J, fSolver->f,fVec);
:info:build                             ~~~~~~~  ^
:info:build /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_root5/root5/work/root-5-34-34/math/mathmore/src/GSLMultiFit.h:153:45: error: no member named 'J' in 'gsl_multifit_fdfsolver'
:info:build       int ret = gsl_multifit_covar(fSolver->J, kEpsrel, fCov);
:info:build                                    ~~~~~~~  ^

**Comment by zoglauer** [comment]
There is an incompatibility between the install gsl version and the one ROOT expects. Please use the ROOT builtin version of GSL:

Modify config/build-root.sh and add AFTER the other CONFIGUREOPTIONS:
CONFIGUREOPTIONS+=" -Dbuiltin_gsl=ON"
