### ISSUE TITLE
Terminal freezes when opening tabs in MEGAlib environment

### ISSUE THREAD

**Issue by mateofa** [zoglauer/megalib#70]
I've been struggling with this problem since I installed MEGAlib. Whenever I activate the environment and try opening a new tab in the terminal, the terminal freezes. I don't have this problem unless I'm using the MEGAlib environment. Another weird thing is that when I open a new tab, the directory path where I'm at is printed repeatedly. I tried re-installing MEGAlib pulling the latest setup script, but results are the same.
Has anyone experienced something similar when loading the MEGAlib environment?

Running: macOS Monterey 12.2.1

**Comment by zoglauer** [comment]
Hello,

Yes, somebody else reported this to me.
However, I cannot reproduce it on my Mac (iMac M1 also with Monterey 12.2.1)

The solution was to use iTerm2 terminal app instead of the built-in one. 

If you have any additional info to help me figure this out, that would be great.
You are using zsh, right?
For example, what is in your ~/.zsh and ~/.zprofile files?

Thanks,
Andreas

**Comment by zoglauer** [comment]
Hello,

You have nothing MEGAlib related in your files!

Once you have installed iTerm2, could you start the built-in terminal app in "fresh" mode, i.e. without restoring old sessions.
You can do this in the (iTeem2) terminal via:
open -F -a Terminal
There is probably a better way to do that, but that's the only one I know.

Best,
Andreas

**Comment by mateofa** [comment]
Hello Andreas,

The iTerm2 works perfectly fine, I haven't had any problems so far. Thanks again for the suggestion!

Mateo

**Comment by zoglauer** [comment]
I figured out another way to remove the saved state of the Terminal app, which does not require iTerm2:

In the Finder use Go -> Go to folder and type:
/Users/<your user name>/Library/Saved Application State
In this folder delete:
com.apple.Terminal.savedState
