### ISSUE TITLE
ERROR: Unable to find a suitable ROOT tar ball

### ISSUE THREAD

**Issue by miguelfmoita** [zoglauer/megalib#72]
Hello,

I am having a problem during the installation on maxOs Montery. Tried to install the root external but did not work.
Here is the log

Setting up ROOT...

Verifying chosen configuration options:

 * Using this environment file: /Users/miguelmoita/MEGAlib/new-source-megalib.sh
 * Using this maximum number of threads: 4
 * Using no debugging code
 * Don't apply MEGAlib internal ROOT and Geant4 patches
 * Don't clean up intermediate build files
 * Clearing the environment paths LD_LIBRARY_PATH, CPATH
 
 
Getting ROOT...
Looking for ROOT version 6.24 with latest patch on the ROOT website --- sometimes this takes a few minutes...
Trying to find root_v6.24.00.source.tar.gz...
Trying to find root_v6.24.02.source.tar.gz...
Trying to find root_v6.24.04.source.tar.gz...
ERROR: Unable to find a suitable ROOT tar ball
 
ERROR: Something went wrong during the ROOT setup.
       Please check the *whole* file /Users/miguelmoita/MEGAlib/external/RootBuildLog.txt for errors.
 
       Since this is an issue with ROOT and not MEGAlib, please try to google the error message, 
       because other ROOT users might face the same issue.
 
       If that fails, please take a look if you find the issue here (look at open and closed issues):
       https://github.com/zoglauer/megalib/issues
 
       If not, please add your problem there and attach your RootBuildLog.txt.

**Comment by zoglauer** [comment]
It works now. My guess is that the ROOT website was down.

**Comment by miguelfmoita** [comment]
Yes, it worked today. Thank you!
