### ISSUE TITLE
unsupported maths function

### ISSUE THREAD

**Issue by grferna** [zoglauer/megalib#74]
Hello,

I have a very strange error:

Stage 1 (reading of file(s)) finished after 0.00623735 sec
Stage 2 (evaluating constants and maths) finished after 0.112907 sec
Stage 3 (evaluating vectors) finished after 0.113518 sec
Stage 4 (evaluating for loops) finished after 0.125575 sec
Stage 5 (evaluating random numbers) finished after 0.125659 sec
MTokenizer::CheckMaths: Unidentifiable maths object: =
   ***  Error  ***  in setup file /data/users/grferna/AHEAD/COMCUBE/Background/COMCUBE_v132.geo.setup at line 361:
"  If {1 <= 0}"
Cannot parse maths -- typo or unsupported maths function.
Stopping to scan geometry file!
ERROR: Unable to initalize detector
An error occurred during initializtion of Geant4

I've just installed the last version following the MEGALib documentation on two different PCs with ubuntu 20.04.4 LTS.
And just in one of them I have this error.
I don't know what's the problem, 
Did I miss some external packages? 

Gonzalo.

**Comment by zoglauer** [comment]
Which MEGAlib version are you using?I thought I fixed that some time ago.On Oct 21, 2022, at 10:55, grferna ***@***.***> wrote:﻿
Hello,
I have a very strange error:
Stage 1 (reading of file(s)) finished after 0.00623735 sec
Stage 2 (evaluating constants and maths) finished after 0.112907 sec
Stage 3 (evaluating vectors) finished after 0.113518 sec
Stage 4 (evaluating for loops) finished after 0.125575 sec
Stage 5 (evaluating random numbers) finished after 0.125659 sec
MTokenizer::CheckMaths: Unidentifiable maths object: =
***  Error  ***  in setup file /data/users/grferna/AHEAD/COMCUBE/Background/COMCUBE_v132.geo.setup at line 361:
"  If {1 <= 0}"
Cannot parse maths -- typo or unsupported maths function.
Stopping to scan geometry file!
ERROR: Unable to initalize detector
An error occurred during initializtion of Geant4
I've just installed the last version following the MEGALib documentation on two different PCs with ubuntu 20.04.4 LTS.
And just in one of them I have this error.
I don't know what's the problem,
Did I miss some external packages?
Gonzalo.

**Comment by grferna** [comment]
I have compile the main branch

**Comment by grferna** [comment]
I've just compiled the MEGAlib_v4-alpha branch and now there is no errors.

**Comment by zoglauer** [comment]
Hi,

Thanks for reporting, I fixed it in main (v4-alpha got merged into main).

Thanks,
Andreas
