### ISSUE TITLE
setup script with debug=strong fails to build ROOT

### ISSUE THREAD

**Issue by markbandstra** [zoglauer/megalib#9]
The main setup.sh script [help text says](https://github.com/zoglauer/megalib/blob/fd9891ac22f53fbbe6b8bdbc52cd62be574f7d59/setup.sh#L55-L56):

> --debug=[off/no, on/yes, strong/hard]
    Debugging options for ROOT, Geant4 & MEGAlib (Default is on for MEGAlib, but off for ROOT and Geant4)

The build-root.sh [help text says](https://github.com/zoglauer/megalib/blob/fd9891ac22f53fbbe6b8bdbc52cd62be574f7d59/config/build-root.sh#L74-L75):

> --debug=[off/no, on/yes, strong/hard]
    Default is on.

However, calling setup.sh with --debug=strong or --debug=hard fails to build ROOT because [only off/no or on/yes are allowed in build-root.sh](https://github.com/zoglauer/megalib/blob/fd9891ac22f53fbbe6b8bdbc52cd62be574f7d59/config/build-root.sh#L177-L192).

Though I haven't gotten there yet, this problem should also happen when building Geant4. Once again the [help text says](https://github.com/zoglauer/megalib/blob/fd9891ac22f53fbbe6b8bdbc52cd62be574f7d59/config/build-geant4.sh#L55-L56):

> --debug=[off/no, on/yes, strong/hard]
    Default is on.

But the [same logic is used in build-geant4.sh](https://github.com/zoglauer/megalib/blob/fd9891ac22f53fbbe6b8bdbc52cd62be574f7d59/config/build-geant4.sh#L157-L172).

**Comment by zoglauer** [comment]
Hi Mark,

This is a bug in the help text. There is no strong/hard debug mode, just a strong/hard optimization.
I fixed in the latest version.

Cheers,
Andreas

**Comment by markbandstra** [comment]
Thanks Andreas.

I noticed that the logic in [setup.sh still allows strong/hard for debug](https://github.com/zoglauer/megalib/blob/a7b39fe5653b5e6878d54b4cab8e00d8d2f479de/setup.sh#L385-L387).
