### ISSUE TITLE
Issue with building develop-cosi

### ISSUE THREAD

**Issue by parshadkp** [zoglauer/megalib#96]
I am having issuing with building the develop-cosi branch. It seems to compile fine but I cannot run anything through it. I am on macOS Sonoma 14.5 with Xcode 15.1.

(base) parshad@heselt005 MEGAlib % geomega
dyld[91911]: Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <739C2A19-DB87-37C1-9B99-034B7CA3E980> /opt/local/lib/libhealpix_cxx.3.dylib
  Reason: tried: '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/MEGAlib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/MEGAlib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/geant4_v11.2.2/lib/Geant4-11.2.2/../libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/external/geant4_v10.02.p03/lib/Geant4-10.2.3/../libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/geant4_v11.2.2/lib/Geant4-11.2.2/../libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/geant4_v11.2.2/lib/Geant4-11.2.2/../libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib/geant4_v10.02.p03/lib/Geant4-10.2.3/../libc++.1.dylib' (no such file), '/libc++.1.dylib' (no such file), '/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/libexec/llvm-16/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libc++.1.dylib' (no such file), '/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/parshad/Software/MEGAlib_cosi-develop/megalib/external/root_v6.28.12/lib/libc++.1.dylib' (no such file), '/opt/local/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libc++.1.dylib' (no such file)

**Comment by zoglauer** [comment]
I was able to reproduce the problem.

Since the error references  /opt/local/lib/libhealpix_cxx.3.dylib, it seems to originate from macports.
I switched to homebrew and the error went away.

Thus not a MEGAlib but a macports issue.

If you want to keep using macports, try to reinstall macports.

**Comment by zoglauer** [comment]
Reinstalling just libhealpix_cxx.3 fixed it, too

**Comment by parshadkp** [comment]
How do you reinstall libhealpix_cxx.3?
